name: Run test case

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
      
        steps:
        - uses: actions/checkout@v1
        - name: Code analysis
          run: |
            make xref
            make dialyzer
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: _build/test/logs
